#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/bugsx -a -d /usr/share/doc/bugsx ]; then
   ln -sf ../share/doc/bugsx /usr/doc/bugsx
  fi
fi

if test -x /usr/bin/update-menus; then update-menus; fi